replicaCount: 1

image:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

license:
  enabled: true
  secretName: hello-license
  mountPath: /etc/license/license.dat
  ## uncommented following lines to create secret with specified "data"
  data: |
    This is my license file
