replicaCount: 1

image:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

licenseUpdate:
  enabled: false 
  secretName: hello-license-import 
  # data: 
  #   license: |
  #     < changeme, provide license file content>
  #   auth:
  #     username: admin
  #     password: changeme

